package com.myspace.test_githooks_kube;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class A implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String x;

	public A() {
	}

	public java.lang.String getX() {
		return this.x;
	}

	public void setX(java.lang.String x) {
		this.x = x;
	}

	public A(java.lang.String x) {
		this.x = x;
	}

}