package com.myspace.test_githooks_kube;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class B implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public B() {
    }




}